"""Plot CSV records produced by teleop_vr_send.py.

Example:
    python -m teleop_vr.plot_teleop_vr_records records/test01_converted.csv
    python -m teleop_vr.plot_teleop_vr_records --raw records/test01_vr_raw.csv records/test01_converted.csv
    python -m teleop_vr.plot_teleop_vr_records --network --raw records/test01_vr_raw.csv
    python -m teleop_vr.plot_teleop_vr_records records/test01_converted.csv --all --save records/test01_plot.png
"""

from __future__ import annotations

import argparse
import csv
import math
from collections.abc import Sequence
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot VR raw and converted teleop records saved by teleop_vr_send.py.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "converted_csv",
        type=Path,
        nargs="?",
        help="Path to *_converted.csv generated by teleop_vr_send.py --record.",
    )
    parser.add_argument(
        "--raw",
        type=Path,
        default=None,
        help="Path to *_vr_raw.csv. Required for --network if converted_csv is omitted.",
    )
    parser.add_argument(
        "--robot-state",
        type=Path,
        default=None,
        help="Path to *_robot_state.csv for robot command/state/error diagnostics.",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
    help="Optional image path to save the plot. Multi-figure modes add suffixes.",
    )
    view_group = parser.add_mutually_exclusive_group()
    view_group.add_argument(
        "--network",
        action="store_true",
        help="Plot network timing/jitter diagnostics instead of trajectory data.",
    )
    view_group.add_argument(
        "--all",
        action="store_true",
        help="Plot both trajectory and network diagnostics.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open an interactive matplotlib window.",
    )
    parser.add_argument(
        "--jitter-threshold-ms",
        type=float,
        default=5.0,
        help="Absolute jitter threshold used for the Summary jitter count.",
    )
    return parser.parse_args()


def _infer_raw_path(converted_path: Path) -> Path:
    name = converted_path.name
    if name.endswith("_converted.csv"):
        return converted_path.with_name(name.removesuffix("_converted.csv") + "_vr_raw.csv")
    return converted_path.with_name(converted_path.stem + "_vr_raw.csv")


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"CSV not found: {path}")
    with path.open(newline="", encoding="utf-8") as csv_file:
        return list(csv.DictReader(csv_file))


def _to_float(value: str | None) -> float:
    if value is None:
        return math.nan
    text = value.strip()
    if text == "" or text.lower() == "none":
        return math.nan
    return float(text)


def _series(rows: Sequence[dict[str, str]], column: str) -> list[float]:
    return [_to_float(row.get(column)) for row in rows]


def _relative_time(rows: Sequence[dict[str, str]], column: str) -> list[float]:
    values = _series(rows, column)
    finite_values = [value for value in values if math.isfinite(value)]
    if not finite_values:
        return list(range(len(rows)))
    start = finite_values[0]
    return [value - start if math.isfinite(value) else math.nan for value in values]


def _first_finite(values: Sequence[float]) -> float:
    for value in values:
        if math.isfinite(value):
            return value
    return math.nan


def _relative_to_start(values: Sequence[float], start: float) -> list[float]:
    if not math.isfinite(start):
        return list(range(len(values)))
    return [value - start if math.isfinite(value) else math.nan for value in values]


def _trajectory_time_axes(
    raw_rows: Sequence[dict[str, str]],
    converted_rows: Sequence[dict[str, str]],
) -> tuple[list[float], list[float], list[float]]:
    raw_received = _series(raw_rows, "received_at_monotonic_s")
    sent_at = _series(converted_rows, "sent_at_monotonic_s")

    # Converted rows now represent actual sender commands, so converted target and
    # sent target share sent_at_monotonic_s as their plotting timestamp.
    start = _first_finite(sent_at)
    if not math.isfinite(start):
        start = _first_finite(raw_received)

    return (
        _relative_to_start(raw_received, start),
        _relative_to_start(sent_at, start),
        _relative_to_start(sent_at, start),
    )


def _diff(values: Sequence[float], *, scale: float = 1.0) -> list[float]:
    deltas: list[float] = []
    previous: float | None = None
    for value in values:
        if previous is None or not math.isfinite(value) or not math.isfinite(previous):
            deltas.append(math.nan)
        else:
            deltas.append((value - previous) * scale)
        previous = value
    return deltas


def _diff_finite_samples(values: Sequence[float], *, scale: float = 1.0) -> list[float]:
    deltas: list[float] = []
    previous: float | None = None
    for value in values:
        if not math.isfinite(value):
            deltas.append(math.nan)
            continue
        if previous is None:
            deltas.append(math.nan)
        else:
            deltas.append((value - previous) * scale)
        previous = value
    return deltas


def _last_row_per_source_frame(rows: Sequence[dict[str, str]]) -> list[dict[str, str]]:
    """Keep one completed raw record per VR source frame.

    HTS can update the assembled HandFrame twice for the same source_frame_seq
    when wrist and landmarks packets arrive separately. Frame-rate and jitter
    statistics should count the VR source frame once, otherwise the short
    wrist/landmarks assembly interval pulls the mean below the real frame dt.
    """
    if not rows or "source_frame_seq" not in rows[0]:
        return list(rows)

    frame_rows: list[dict[str, str]] = []
    current_seq = math.nan
    current_row: dict[str, str] | None = None
    saw_finite_seq = False

    for row in rows:
        seq = _to_float(row.get("source_frame_seq"))
        if not math.isfinite(seq):
            if current_row is not None:
                frame_rows.append(current_row)
                current_row = None
            frame_rows.append(row)
            current_seq = math.nan
            continue

        saw_finite_seq = True
        if current_row is not None and seq != current_seq:
            frame_rows.append(current_row)
        current_seq = seq
        current_row = row

    if current_row is not None:
        frame_rows.append(current_row)

    return frame_rows if saw_finite_seq else list(rows)


def _valid(values: Sequence[float]) -> list[float]:
    return [value for value in values if math.isfinite(value)]


def _percentile(values: Sequence[float], fraction: float) -> float:
    finite = sorted(_valid(values))
    if not finite:
        return math.nan
    index = (len(finite) - 1) * fraction
    low = int(math.floor(index))
    high = int(math.ceil(index))
    if low == high:
        return finite[low]
    weight = index - low
    return finite[low] * (1.0 - weight) + finite[high] * weight


def _summary_text(name: str, values: Sequence[float], unit: str) -> str:
    finite = _valid(values)
    if not finite:
        return f"{name}: n=0"
    mean = sum(finite) / len(finite)
    return (
        f"{name}: n={len(finite)} "
        f"mean={mean:.3f}{unit} "
        f"p50={_percentile(finite, 0.50):.3f}{unit} "
        f"p95={_percentile(finite, 0.95):.3f}{unit} "
        f"max={max(finite):.3f}{unit}"
    )


def _frame_rate_summary(name: str, dt_ms: Sequence[float]) -> str:
    finite = [value for value in _valid(dt_ms) if value > 0.0]
    if not finite:
        return f"{name}: fps n=0"
    mean_dt_ms = sum(finite) / len(finite)
    max_dt_ms = max(finite)
    avg_fps = 1000.0 / mean_dt_ms
    worst_fps = 1000.0 / max_dt_ms
    return (
        f"{name}: avg_fps={avg_fps:.2f}Hz "
        f"worst_fps={worst_fps:.2f}Hz "
        f"max_dt={max_dt_ms:.3f}ms"
    )


def _draw_mean_line(ax: object, values: Sequence[float], *, unit: str) -> None:
    finite = _valid(values)
    if not finite:
        return
    mean = sum(finite) / len(finite)
    ax.axhline(mean, color="tab:orange", linestyle="--", linewidth=1.1, label=f"mean={mean:.3f}{unit}")
    ax.text(
        0.99,
        0.92,
        f"mean={mean:.3f}{unit}",
        transform=ax.transAxes,
        ha="right",
        va="top",
        bbox={"facecolor": "white", "edgecolor": "tab:orange", "alpha": 0.75},
    )


def _has_columns(rows: Sequence[dict[str, str]], columns: Sequence[str]) -> bool:
    if not rows:
        return False
    return all(column in rows[0] for column in columns)


def _plot_channel(
    ax: object,
    time_s: Sequence[float],
    rows: Sequence[dict[str, str]],
    column: str,
    *,
    title: str,
    ylabel: str,
    label: str | None = None,
    scale: float = 1.0,
) -> None:
    ax.set_title(title)
    ax.plot(time_s, [value * scale for value in _series(rows, column)], label=label or column)
    ax.set_ylabel(ylabel)
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)


def _plot_two_channels(
    ax: object,
    first_time_s: Sequence[float],
    first_rows: Sequence[dict[str, str]],
    first_column: str,
    second_time_s: Sequence[float],
    second_rows: Sequence[dict[str, str]],
    second_column: str,
    *,
    title: str,
    ylabel: str,
    first_label: str,
    second_label: str,
    first_scale: float = 1.0,
    second_scale: float = 1.0,
) -> None:
    ax.set_title(title)
    ax.plot(
        first_time_s,
        [value * first_scale for value in _series(first_rows, first_column)],
        label=first_label,
    )
    ax.plot(
        second_time_s,
        [value * second_scale for value in _series(second_rows, second_column)],
        label=second_label,
    )
    ax.set_ylabel(ylabel)
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)


def _plot_target_records(
    raw_rows: list[dict[str, str]],
    converted_rows: list[dict[str, str]],
    *,
    target_prefix: str,
    title: str,
    include_vr: bool,
) -> object:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError("matplotlib is required: pip install matplotlib") from exc

    raw_time, converted_time, sent_time = _trajectory_time_axes(raw_rows, converted_rows)
    target_time = sent_time
    if target_prefix == "raw_target":
        target_time = converted_time

    rows = 5 if include_vr else 3
    fig, axes = plt.subplots(rows, 3, figsize=(18, 4 * rows), sharex=False)
    fig.suptitle(f"{title} (sender monotonic time)")

    row_offset = 0
    if include_vr:
        for col, axis_name in enumerate(("x", "y", "z")):
            raw_axis = f"wrist_{axis_name}"
            if raw_rows and _has_columns(raw_rows, [raw_axis]):
                _plot_channel(
                    axes[0, col],
                    raw_time,
                    raw_rows,
                    raw_axis,
                    title=f"Raw VR Wrist {axis_name.upper()}",
                    ylabel="cm",
                    label=axis_name,
                )
            else:
                axes[0, col].axis("off")

            _plot_channel(
                axes[1, col],
                converted_time,
                converted_rows,
                f"vr_{axis_name}",
                title=f"Converted VR {axis_name.upper()}",
                ylabel="cm",
                label=axis_name,
            )
        row_offset = 2

    for col, axis_name in enumerate(("roll", "pitch", "yaw")):
        pos_axis = ("x", "y", "z")[col]
        _plot_channel(
            axes[row_offset, col],
            target_time,
            converted_rows,
            f"{target_prefix}_{pos_axis}",
            title=f"{title} {pos_axis.upper()}",
            ylabel="cm",
            label=pos_axis,
        )
        _plot_channel(
            axes[row_offset + 1, col],
            target_time,
            converted_rows,
            f"{target_prefix}_{axis_name}",
            title=f"{title} {axis_name.title()}",
            ylabel="rad",
            label=axis_name,
        )

    gripper_column = "raw_gripper_pos" if target_prefix == "raw_target" else "sent_gripper_pos"
    gripper_ax = axes[row_offset + 2, 0]
    _plot_channel(
        gripper_ax,
        target_time,
        converted_rows,
        gripper_column,
        title=f"{title} Gripper",
        ylabel="cm",
        label="gripper",
    )
    axes[row_offset + 2, 1].axis("off")
    axes[row_offset + 2, 2].axis("off")

    for row in axes:
        for ax in row:
            if ax.axison:
                ax.set_xlabel("time from first sent command (s)")

    fig.tight_layout()
    return fig


def _plot_records(
    raw_rows: list[dict[str, str]],
    converted_rows: list[dict[str, str]],
) -> list[tuple[str, object]]:
    return [
        (
            "raw_target",
            _plot_target_records(
                raw_rows,
                converted_rows,
                target_prefix="raw_target",
                title="Raw Target Before Postprocess",
                include_vr=True,
            ),
        ),
        (
            "sent_target",
            _plot_target_records(
                raw_rows,
                converted_rows,
                target_prefix="sent_target",
                title="Sent Target After Postprocess",
                include_vr=True,
            ),
        ),
    ]


def _plot_network(raw_rows: list[dict[str, str]], *, jitter_threshold_ms: float) -> object:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError("matplotlib is required: pip install matplotlib") from exc

    frame_rows = _last_row_per_source_frame(raw_rows)
    frame_time = _relative_time(frame_rows, "received_at_monotonic_s")
    raw_time = _relative_time(raw_rows, "received_at_monotonic_s")
    recv_dt_ms = _diff(_series(frame_rows, "received_at_monotonic_s"), scale=1000.0)
    sdk_recv_dt_ms = _diff(_series(frame_rows, "recv_ts_ns"), scale=1e-6)
    source_dt_ms = _diff(_series(frame_rows, "source_ts_ns"), scale=1e-6)
    jitter_ms = [
        recv_dt - source_dt
        if math.isfinite(recv_dt) and math.isfinite(source_dt)
        else math.nan
        for recv_dt, source_dt in zip(recv_dt_ms, source_dt_ms, strict=True)
    ]
    source_seq = _series(frame_rows, "source_frame_seq")
    dropped_frames = []
    previous_seq: float | None = None
    for seq in source_seq:
        if previous_seq is None or not math.isfinite(seq) or not math.isfinite(previous_seq):
            dropped_frames.append(math.nan)
        else:
            dropped_frames.append(max(0.0, seq - previous_seq - 1.0))
        previous_seq = seq
    record_index_gap = []
    previous_record_index: float | None = None
    for record_index in _series(raw_rows, "record_index"):
        if (
            previous_record_index is None
            or not math.isfinite(record_index)
            or not math.isfinite(previous_record_index)
        ):
            record_index_gap.append(math.nan)
        else:
            record_index_gap.append(max(0.0, record_index - previous_record_index - 1.0))
        previous_record_index = record_index

    wrist_landmark_gap_ms = [
        (landmarks - wrist) / 1e6
        if math.isfinite(landmarks) and math.isfinite(wrist)
        else math.nan
        for wrist, landmarks in zip(
            _series(raw_rows, "wrist_recv_ts_ns"),
            _series(raw_rows, "landmarks_recv_ts_ns"),
            strict=True,
        )
    ]

    fig, axes = plt.subplots(4, 2, figsize=(16, 14), sharex=False)
    fig.suptitle("VR Raw Network Diagnostics")

    axes[0, 0].set_title("Local received_at Inter-arrival")
    axes[0, 0].plot(frame_time, recv_dt_ms, label="local received_at dt")
    _draw_mean_line(axes[0, 0], recv_dt_ms, unit="ms")
    axes[0, 0].set_ylabel("interval (ms)")
    axes[0, 0].legend(loc="best")
    axes[0, 0].grid(True, alpha=0.3)

    axes[0, 1].set_title("SDK recv_ts Inter-arrival")
    axes[0, 1].plot(frame_time, sdk_recv_dt_ms, label="sdk recv_ts dt")
    _draw_mean_line(axes[0, 1], sdk_recv_dt_ms, unit="ms")
    axes[0, 1].set_ylabel("interval (ms)")
    axes[0, 1].legend(loc="best")
    axes[0, 1].grid(True, alpha=0.3)

    axes[1, 0].set_title("VR source_ts Inter-arrival")
    axes[1, 0].plot(frame_time, source_dt_ms, label="source dt")
    _draw_mean_line(axes[1, 0], source_dt_ms, unit="ms")
    axes[1, 0].set_ylabel("interval (ms)")
    axes[1, 0].legend(loc="best")
    axes[1, 0].grid(True, alpha=0.3)

    axes[1, 1].set_title("Network Jitter Estimate")
    axes[1, 1].plot(frame_time, jitter_ms, label="local received_at dt - source dt")
    axes[1, 1].axhline(0.0, color="black", linewidth=0.8, alpha=0.4)
    axes[1, 1].axhline(jitter_threshold_ms, color="red", linestyle="--", linewidth=0.8, alpha=0.5)
    axes[1, 1].axhline(-jitter_threshold_ms, color="red", linestyle="--", linewidth=0.8, alpha=0.5)
    _draw_mean_line(axes[1, 1], jitter_ms, unit="ms")
    axes[1, 1].set_ylabel("jitter (ms)")
    axes[1, 1].legend(loc="best")
    axes[1, 1].grid(True, alpha=0.3)

    axes[2, 0].set_title("Estimated Drops From Source Frame Sequence")
    axes[2, 0].step(frame_time, dropped_frames, where="post", label="dropped frames")
    _draw_mean_line(axes[2, 0], dropped_frames, unit="")
    axes[2, 0].set_ylabel("frames")
    axes[2, 0].legend(loc="best")
    axes[2, 0].grid(True, alpha=0.3)

    axes[2, 1].set_title("Wrist/Landmarks Assembly Gap")
    axes[2, 1].plot(raw_time, wrist_landmark_gap_ms, label="landmarks recv - wrist recv")
    axes[2, 1].axhline(0.0, color="black", linewidth=0.8, alpha=0.4)
    _draw_mean_line(axes[2, 1], wrist_landmark_gap_ms, unit="ms")
    axes[2, 1].set_ylabel("gap (ms)")
    axes[2, 1].legend(loc="best")
    axes[2, 1].grid(True, alpha=0.3)

    axes[3, 0].set_title("Recorder Continuity")
    axes[3, 0].step(raw_time, record_index_gap, where="post", label="record_index gaps")
    _draw_mean_line(axes[3, 0], record_index_gap, unit="")
    axes[3, 0].set_ylabel("rows")
    axes[3, 0].legend(loc="best")
    axes[3, 0].grid(True, alpha=0.3)

    axes[3, 1].set_title("Summary")
    axes[3, 1].axis("off")
    jitter_count = sum(
        1 for value in jitter_ms if math.isfinite(value) and abs(value) >= jitter_threshold_ms
    )
    summary_lines = [
        f"raw rows={len(raw_rows)} source frames={len(frame_rows)}",
        "",
        _summary_text("local inter-arrival", recv_dt_ms, "ms"),
        _summary_text("sdk inter-arrival", sdk_recv_dt_ms, "ms"),
        _summary_text("source inter-arrival", source_dt_ms, "ms"),
        _summary_text("jitter", jitter_ms, "ms"),
        _summary_text("assembly gap", wrist_landmark_gap_ms, "ms"),
        "",
        _frame_rate_summary("local received_at", recv_dt_ms),
        _frame_rate_summary("sdk recv_ts", sdk_recv_dt_ms),
        _frame_rate_summary("source_ts", source_dt_ms),
        f"jitter count >= {jitter_threshold_ms:.3f}ms: {jitter_count}",
        f"estimated dropped frames: {sum(_valid(dropped_frames)):.0f}",
        f"record_index gaps: {sum(_valid(record_index_gap)):.0f}",
    ]
    if not any(math.isfinite(value) for value in source_dt_ms):
        summary_lines.append("source_ts_ns unavailable: source fps/jitter are incomplete")
    axes[3, 1].text(
        0.0,
        1.0,
        "\n".join(summary_lines),
        va="top",
        ha="left",
        family="monospace",
    )

    for row in axes:
        for ax in row:
            if ax.axison:
                ax.set_xlabel("time (s)")

    fig.tight_layout()
    return fig


def _plot_robot_state(rows: list[dict[str, str]]) -> object:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError("matplotlib is required: pip install matplotlib") from exc

    time_s = _relative_time(rows, "sent_at_monotonic_s")
    fig, axes = plt.subplots(4, 3, figsize=(18, 14), sharex=True)
    fig.suptitle("Robot State Diagnostics")

    for col, axis_name in enumerate(("x", "y", "z")):
        axes[0, col].set_title(f"Position {axis_name.upper()}")
        axes[0, col].plot(time_s, _series(rows, f"cmd_{axis_name}"), label="cmd")
        axes[0, col].plot(time_s, _series(rows, f"state_{axis_name}"), label="state")
        axes[0, col].set_ylabel("m")
        axes[0, col].legend(loc="best")
        axes[0, col].grid(True, alpha=0.3)

    for col, axis_name in enumerate(("roll", "pitch", "yaw")):
        axes[1, col].set_title(axis_name.title())
        axes[1, col].plot(time_s, _series(rows, f"cmd_{axis_name}"), label="cmd")
        axes[1, col].plot(time_s, _series(rows, f"state_{axis_name}"), label="state")
        axes[1, col].set_ylabel("rad")
        axes[1, col].legend(loc="best")
        axes[1, col].grid(True, alpha=0.3)

    for col, axis_name in enumerate(("x", "y", "z")):
        values = _series(rows, f"error_{axis_name}")
        axes[2, col].set_title(f"Position Error {axis_name.upper()}")
        axes[2, col].plot(time_s, values, label=f"error_{axis_name}")
        _draw_mean_line(axes[2, col], values, unit="m")
        axes[2, col].set_ylabel("m")
        axes[2, col].legend(loc="best")
        axes[2, col].grid(True, alpha=0.3)

    axes[3, 0].set_title("Gripper")
    axes[3, 0].plot(time_s, _series(rows, "cmd_gripper_pos"), label="cmd")
    axes[3, 0].plot(time_s, _series(rows, "state_gripper_pos"), label="state")
    axes[3, 0].set_ylabel("m")
    axes[3, 0].legend(loc="best")
    axes[3, 0].grid(True, alpha=0.3)

    axes[3, 1].set_title("Orientation Error Norm")
    ori_error_norm = [
        math.sqrt(roll * roll + pitch * pitch + yaw * yaw)
        if math.isfinite(roll) and math.isfinite(pitch) and math.isfinite(yaw)
        else math.nan
        for roll, pitch, yaw in zip(
            _series(rows, "error_roll"),
            _series(rows, "error_pitch"),
            _series(rows, "error_yaw"),
            strict=True,
        )
    ]
    axes[3, 1].plot(time_s, ori_error_norm, label="orientation error norm")
    _draw_mean_line(axes[3, 1], ori_error_norm, unit="rad")
    axes[3, 1].set_ylabel("rad")
    axes[3, 1].legend(loc="best")
    axes[3, 1].grid(True, alpha=0.3)

    axes[3, 2].set_title("Summary")
    axes[3, 2].axis("off")
    pos_error_norm = [
        math.sqrt(x * x + y * y + z * z)
        if math.isfinite(x) and math.isfinite(y) and math.isfinite(z)
        else math.nan
        for x, y, z in zip(
            _series(rows, "error_x"),
            _series(rows, "error_y"),
            _series(rows, "error_z"),
            strict=True,
        )
    ]
    dt_ms = _diff(_series(rows, "sent_at_monotonic_s"), scale=1000.0)
    summary_lines = [
        f"rows={len(rows)}",
        _summary_text("sample dt", dt_ms, "ms"),
        _frame_rate_summary("robot state sample", dt_ms),
        "",
        _summary_text("position error norm", pos_error_norm, "m"),
        _summary_text("orientation error norm", ori_error_norm, "rad"),
        _summary_text("gripper error", _series(rows, "error_gripper_pos"), "m"),
    ]
    axes[3, 2].text(
        0.0,
        1.0,
        "\n".join(summary_lines),
        va="top",
        ha="left",
        family="monospace",
    )

    for row in axes:
        for ax in row:
            if ax.axison:
                ax.set_xlabel("time from first robot state sample (s)")

    fig.tight_layout()
    return fig


def _save_figure(fig: object, save_path: Path, suffix: str | None = None) -> None:
    path = save_path
    if suffix is not None:
        path = save_path.with_name(f"{save_path.stem}_{suffix}{save_path.suffix}")
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    print(f"saved plot to {path}")


def main() -> int:
    args = _parse_args()
    if args.robot_state is not None:
        robot_state_path = args.robot_state.expanduser().resolve()
        robot_state_rows = _read_csv(robot_state_path)
        if not robot_state_rows:
            raise RuntimeError(f"No robot state records in {robot_state_path}")
        figures = [(None, _plot_robot_state(robot_state_rows))]
        if args.save is not None:
            _save_figure(figures[0][1], args.save.expanduser().resolve(), None)
        if not args.no_show:
            import matplotlib.pyplot as plt

            plt.show()
        return 0

    converted_path = (
        None if args.converted_csv is None else args.converted_csv.expanduser().resolve()
    )
    if args.raw is None:
        if converted_path is None:
            raise RuntimeError("--raw is required when converted_csv is omitted.")
        raw_path = _infer_raw_path(converted_path)
    else:
        raw_path = args.raw.expanduser()
    raw_path = raw_path.resolve()

    raw_rows = _read_csv(raw_path)
    if not raw_rows:
        raise RuntimeError(f"No raw records in {raw_path}")

    converted_rows: list[dict[str, str]] = []
    if not args.network:
        if converted_path is None:
            raise RuntimeError("converted_csv is required for trajectory plots.")
        converted_rows = _read_csv(converted_path)
        if not converted_rows:
            raise RuntimeError(f"No converted records in {converted_path}")

    figures: list[tuple[str | None, object]] = []
    if args.network:
        figures.append((None, _plot_network(raw_rows, jitter_threshold_ms=args.jitter_threshold_ms)))
    elif args.all:
        figures.extend(_plot_records(raw_rows, converted_rows))
        figures.append(("network", _plot_network(raw_rows, jitter_threshold_ms=args.jitter_threshold_ms)))
    else:
        figures.extend(_plot_records(raw_rows, converted_rows))

    if args.save is not None:
        save_path = args.save.expanduser().resolve()
        if len(figures) == 1:
            suffix, fig = figures[0]
            _save_figure(fig, save_path, suffix)
        else:
            for suffix, fig in figures:
                _save_figure(fig, save_path, suffix)

    if not args.no_show:
        import matplotlib.pyplot as plt

        plt.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
